baseurl = "https://www.lxvdo.com"
languageCode = "en"
title = "LXVDO"
theme = "hemingway2"
disqusShortname = "lxvdo"
googleAnalytics = "UA-116832031-1"
description = "My personal blog"
#keywords = ["keyword1", "keyword2"]

[params]
	custom_css = ["css/custom.css"]

#baseURL = "/"
#languageCode = "en-us"
#title = "My New Hugo Site"
#theme = "hemingway2"